[package]
name = "codice-fiscale"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
phf = "0.11.2"
serde = "1.0.203"
serde_json = "1.0.117"

[build-dependencies]
phf_codegen = "0.11.2"
